id: IC4B645C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T21:22:15+00:00'
last_modified: '2022-06-07T16:11:51.129229+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6023
  title: འཕྲིན་ལས་རྒྱ་མཚོའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F84B:
      image_group_id: I1KG2772
      title: ''
      total_pages: 586
      order: 1
      base_file: F84B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
