id: IC4B645C4
legacy_id: P002919
ocr_import_info:
  bdrc_scan_id: W2CZ6023
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T21:18:33'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:02:24.656755+00:00'
last_modified: 2022-09-02 23:03:37.946655
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ6023
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ6023
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཕྲིན་ལས་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ཕུར་བུ་ལྕོག་བློ་བཟང་བྱམས་པ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6598998128196493
  ocr_word_median_confidence_index: 0.6899999976158142
quality: null
bases:
  I1KG2772:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2772
      total_pages: 586
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2772.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6598998128196493
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
